# Generated by Django 2.2.15 on 2020-11-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20201126_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='bceiduser',
            name='has_efiling_early_access',
            field=models.BooleanField(default=False),
        ),
    ]
