# Generated by Django 2.2.15 on 2021-03-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_bceiduser_has_efiling_early_access'),
    ]

    operations = [
         migrations.RunSQL(
            "UPDATE core_bceiduser SET username = user_guid"
        )
    ]
